import {Platform, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import colors from '../utils/colors';

export default StyleSheet.create({
  regularFont: {
    fontSize: 16,
    fontFamily: 'OpenSans-Regular',
    color: colors.darkGrey,
  },
  container: {
    flex: 1,
    backgroundColor: colors.lightRed,
  },
  card: {
    paddingVertical: hp(5),
    borderRadius: hp(3),
    height: hp(70),
    paddingHorizontal: wp(5),
    borderWidth: 2,
    borderColor: colors.silver,
    backgroundColor: colors.white,
    justifyContent: 'flex-start',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  testContainer: {flexGrow: 1, backgroundColor: colors.whiteSmoke},
  progressView: {
    height: hp(5),
    marginVertical: hp(2),
    marginHorizontal: wp(4),
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
  },
  progressBar: {
    height: hp(2),
    width: wp(15),
    borderRadius: hp(3),
  },
  swiperView: {
    bottom: hp(8),
  },
  questOpt: {
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    height: hp(36),
    marginVertical: hp(3),
  },
  options: {
    width: wp(77),
    height: hp(6),
    flexDirection: 'row',
    borderRadius: hp(1.5),
    alignItems: 'center',
    paddingHorizontal: wp(3),
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  padSpace: {paddingHorizontal: wp(2.5)},
  mainButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  m_button: {
    height: hp(6),
    width: wp(30),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: hp(1.5),
  },
  backText: {
    color: colors.darkGrey,
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 16,
  },
  resultView: {
    marginVertical: hp(4),
    width: wp(85),
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: hp(3),
    padding: wp(6),
    paddingVertical: hp(6),
  },
  resultText: {textAlign: 'center', marginVertical: hp(1)},
  resultButton: {
    borderRadius: hp(8),
    backgroundColor: colors.teal,
    width: wp(60),
    height: hp(7),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(2),
  },
  resultButtonText: {fontSize: 16, color: colors.white},
  cardNum: {marginTop: hp(1.5), alignItems: 'center'},
  resultProgress: {
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  midVal: {
    alignSelf: 'center',
    bottom: Platform.OS === 'ios' ? hp(37) : hp(31),
    fontSize: hp(7),
    color: colors.teal,
  },
  graphVal: {
    alignSelf: 'flex-end',
    bottom: Platform.OS === 'ios' ? hp(37) : hp(31),
    fontSize: hp(4),
    color: colors.grey,
  },
  graphValView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp(85),
    marginHorizontal: wp(13.5),
  },
  questNum: {backgroundColor: colors.whiteSmoke, flex: 1},
  resultPage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  itemCenter: {alignItems: 'center'},
  itemCenter1: {alignItems: 'center'},
  checkMark: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? hp(0.75) : hp(0.5),
    left: wp(0.8),
  },
  semiCircle: {height: hp(40), alignItems: 'center'},
  resultPic: {height: hp(35), alignItems: 'center', marginVertical: hp(1)},
});
